<html><body>
<?php
require('header.php');
require('controller.php');

if(isset($_GET['action'])){
	if($_GET['action']=='listOrders'){
		listOrders();
	}
	elseif($_GET['action']=='createOrders'){
		createOrders();
	}
	elseif($_GET['action']=='updateOrders'){
		majOrders();
	}
	elseif($_GET['action']=='deleteOrders'){
		delOrders();
	}
}
else{
	listOrders();
}
?>
</body>
</html>